import React from 'react';
import DataFusionPanel from '../components/DataFusionPanel';

const sources = [
  { source: 'WHO GHO', provider: 'World Health Organization', records: '1,245', license: 'CC BY 4.0', accessed: 'Today', quality: 98 },
  { source: 'OpenWeather', provider: 'OpenWeatherMap', records: 'Live', license: 'Commercial', accessed: 'Live', quality: 95 },
  { source: 'Synthetic Training', provider: 'Generated by Helix', records: '5,000+', license: 'Internal', accessed: 'N/A', quality: 100 },
  { source: 'PIMA Diabetes', provider: 'UCI ML Repo', records: '768', license: 'Public Domain', accessed: 'Phase 9', quality: 92 },
  { source: 'Cleveland Heart', provider: 'UCI ML Repo', records: '303', license: 'Public Domain', accessed: 'Phase 9', quality: 89 },
  { source: 'Kaggle Stroke', provider: 'Kaggle', records: '5,110', license: 'Open', accessed: 'Phase 9', quality: 94 },
];

export default function DataSources() {
  return (
    <div className="space-y-12 animate-fade-in pb-24">
      <div>
        <h1 className="text-3xl font-bold text-helix-text mb-1">Data <span className="text-helix-accent">Sources & Attribution</span></h1>
        <p className="text-helix-text-muted text-sm">Transparent intelligence built on robust public and synthetic datasets.</p>
      </div>
      
      {/* Existing Data Fusion Panel */}
      <DataFusionPanel />

      {/* Dataset Attribution Table */}
      <section className="bg-helix-surface border border-helix-border rounded-3xl p-8">
        <h2 className="text-xl font-bold text-helix-text mb-6">Public Datasets & Citations</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="text-[10px] text-helix-text-muted uppercase tracking-widest border-b border-helix-border">
                <th className="pb-4">Source</th>
                <th className="pb-4">Provider</th>
                <th className="pb-4">Records Used</th>
                <th className="pb-4">License</th>
                <th className="pb-4">Last Accessed</th>
                <th className="pb-4 text-right">Data Quality</th>
              </tr>
            </thead>
            <tbody className="text-sm">
              {sources.map((src, i) => (
                <tr key={i} className="border-b border-helix-border/50 hover:bg-helix-surface-light/30 transition-colors">
                  <td className="py-4 font-bold text-helix-text">{src.source}</td>
                  <td className="py-4 text-helix-text-muted">{src.provider}</td>
                  <td className="py-4 text-helix-accent font-mono">{src.records}</td>
                  <td className="py-4 text-helix-warning/80">{src.license}</td>
                  <td className="py-4 text-helix-text-muted">{src.accessed}</td>
                  <td className="py-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <span className="text-xs font-mono text-helix-success">{src.quality}/100</span>
                      <div className="w-16 h-1.5 bg-helix-surface-light rounded-full overflow-hidden">
                        <div className="h-full bg-helix-success" style={{ width: `${src.quality}%` }} />
                      </div>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Privacy Section */}
      <section className="bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-indigo-500/10 via-helix-surface to-helix-surface border border-helix-border rounded-3xl p-8 lg:p-12">
        <div className="flex items-center gap-4 mb-6">
          <div className="w-12 h-12 rounded-full bg-indigo-500/20 border border-indigo-500/40 flex items-center justify-center text-2xl">
            🔒
          </div>
          <div>
            <h2 className="text-xl font-bold text-helix-text">How We Ensure Data Privacy</h2>
            <p className="text-sm text-indigo-400">Zero-Trust Medical Intelligence</p>
          </div>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-sm">
          <div className="bg-black/30 p-6 rounded-2xl border border-helix-border/50">
            <h4 className="font-bold text-helix-text mb-2 flex items-center gap-2">
              <span className="text-indigo-400">01.</span> Hashed PII
            </h4>
            <p className="text-helix-text-muted leading-relaxed">
              All personal identifiable information (PII) is irreversibly hashed using SHA-256 before ever reaching our ML endpoints. We only analyze physiological patterns.
            </p>
          </div>
          
          <div className="bg-black/30 p-6 rounded-2xl border border-helix-border/50">
            <h4 className="font-bold text-helix-text mb-2 flex items-center gap-2">
              <span className="text-indigo-400">02.</span> Noise Injection
            </h4>
            <p className="text-helix-text-muted leading-relaxed">
              We apply Differential Privacy mechanisms (±2% synthetic noise) to exact locations and temporal stamps, preventing re-identification while preserving cluster accuracy.
            </p>
          </div>
          
          <div className="bg-black/30 p-6 rounded-2xl border border-helix-border/50">
            <h4 className="font-bold text-helix-text mb-2 flex items-center gap-2">
              <span className="text-indigo-400">03.</span> Edge Processing
            </h4>
            <p className="text-helix-text-muted leading-relaxed">
              Biometric signals (like facial asymmetry from Stroke Guard) are processed purely on the edge (browser). No raw image or video data is ever transmitted to the server.
            </p>
          </div>
        </div>
      </section>

    </div>
  );
}
